import type { NextPage } from "next";
import Head from "next/head";
import LineChart from '../components/LineChart';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <LineChart rootStyles={{
          width:'800px',
          height: '500px'
        }}/>
      </main>
    </>
  );
};


export default Home;
