import type { NextPage } from "next";
import Head from "next/head";

// import dynamic from 'next/dynamic';

// const PlotlyGraph = dynamic(
//     () =>
//         import(
//             '../graphs/graph.component'
//         ),
//     {
//         ssr: false,
//         loading: () => <>Loading...</>,
//     },
// );

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>
        
        
        
      </div>
    </>
  );
};

export default Home;
