import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import dynamic from 'next/dynamic';
import { CountsByDateProps, NycDataItem } from "../../types";
import PacmanLoader from 'react-spinners/PacmanLoader';
/**
 * Plotly cannot be used with SSR, this solves the issue
 */
const PlotlyLineChart = dynamic(
  () =>
    import(
      '../components/PlotlyLineChart'
    ),
  {
    ssr: false,
    loading: AppLoader,
  },
);

interface HomePageSsrProps {
  countsByDate: any;
}

const Home: NextPage<HomePageSsrProps> = ({ countsByDate }) => {
  return (
    <>
      <Head>
        <title>Plotly Basic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="box">
        <PlotlyLineChart countsByDate={countsByDate} />
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  let countsByDate: Array<CountsByDateProps> = [];
  let error = null;

  try {
    const DATA_URL = 'https://data.cityofnewyork.us/resource/tg4x-b46p.json';
    const res = await fetch(DATA_URL)
    const data: Array<NycDataItem> = await res.json();
    const filmPermits = data.filter(item => item.eventtype === "Shooting Permit");
    const dates = [...new Set(filmPermits.map(item => item.enteredon.slice(0, 10)))]

    countsByDate = dates.map(time => {
      let date = time;
      let count = 0;
      filmPermits.forEach(item => {
        let timeStamp = item.enteredon.slice(0, 10);
        if (timeStamp === date) {
          count++;
        }
      })
      return {
        date,
        count
      }
    })
  } catch (err) {
    console.log(err)
    // Send to reporting servicfe when error
  }
  return {
    props: {
      countsByDate,
      error
    },
  }
}

function AppLoader() {
  return (
    <div className="loaderContainer">
      <div className="loader">
        <PacmanLoader size={100} color='#FFCB69' />
      </div>
    </div>
  )
}

export default Home;
